### ISSUE TITLE
License Request

### ISSUE THREAD

**Issue by FedericoCalzoni** [riyanj220/Gym-Management-System---Django#1]
I would like to clone and fork this repository, but I want to avoid any potential copyright infringement. Could you please add a license to the repository so that I know what I am allowed to do?

**Comment by riyanj220** [comment]
Hello Federico,

Thank you for reaching out and for your interest in my project.

I’ve added the MIT License to the repository, so you’re free to clone,
fork, and modify it as needed.

If you require any additional features or specific customizations for your
gym project, I'd be happy to help! Please note that additional development
or customization would be a paid service. Feel free to reach out if you'd
like to discuss any specific requirements.

Best regards,
Riyan Jamil

**Comment by FedericoCalzoni** [comment]
Thank you!
